name: Deploy app

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_call:
    secrets:
      SSH_USERNAME:
        required: true
      SSH_HOSTNAME:
        required: true
      SSH_PRIVATE_KEY:
        required: true

jobs:
  build:
    uses: ./.github/workflows/build.yml

  test:
    needs: build
    uses: ./.github/workflows/test.yml

  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          lfs: true

      - name: Download website
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5
        with:
          name: website
          path: website/dist

      - name: Deploy
        uses: ./.github/actions/rsync
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          options: --archive --delete --exclude-from .rsyncignore
          source: website/dist/
          target: ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOSTNAME }}:~/${{ github.event_name == 'pull_request' && 'dev.feeds.unindented.org' || 'feeds.unindented.org' }}/
