name: Refresh feeds

on:
  schedule:
    - cron: "0 */12 * * *" # Run every 12 hours
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write

env:
  NODE_VERSION: 22
  OPML_FILE_PATH: feeds.opml
  SQLITE_FILE_PATH: feeds.sqlite3

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          lfs: true

      - name: Configure account
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Set up pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4

      - name: Set up Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Refresh SQLite database
        run: pnpm run refresh $(realpath $OPML_FILE_PATH) $(realpath $SQLITE_FILE_PATH)

      - name: Commit and push SQLite database if changed
        run: |
          git add feeds.sqlite3
          git commit -m "chore: update SQLite database" \
            && git push \
            || echo "No changes"

  deploy:
    needs: refresh
    uses: ./.github/workflows/deploy.yml
    secrets:
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_HOSTNAME: ${{ secrets.SSH_HOSTNAME }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
