name: Test app

on:
  workflow_call:

env:
  NODE_VERSION: 22

jobs:
  test:
    runs-on: ubuntu-latest
    # Using containers to have a consistent environment when doing visual
    # regression testing across different operating systems.
    # https://playwright.dev/docs/ci#via-containers
    container:
      image: mcr.microsoft.com/playwright:v1.55.1-noble@sha256:2f29369043d81d6d69a815ceb80760f55e85f5020371ad06a4d996f18503ad1c
    env:
      # Firefox is unable to launch if the `HOME` folder isn't owned by the
      # current user.
      HOME: /root
    steps:
      - name: Install Git LFS
        run: |
          ARCH=$(uname -m | sed 's/i386/386/;s/x86_64/amd64/;s/armv7l/arm/;s/aarch64/arm64/')
          VERSION=$(curl --no-progress-meter https://api.github.com/repos/git-lfs/git-lfs/releases/latest | grep -oP '"tag_name": "\K[^"]+')
          curl -L "https://github.com/git-lfs/git-lfs/releases/download/${VERSION}/git-lfs-linux-${ARCH}-${VERSION}.tar.gz" | tar -xz
          mkdir -p "$HOME/.local"
          git-lfs-*/install.sh --local
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          lfs: true

      - name: Download website
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5
        with:
          name: website
          path: website/dist

      - name: Set up pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4

      - name: Set up Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: |
          pnpm run test:types
          pnpm run test:lint
          pnpm run test:unit
          pnpm run test:e2e

      - name: Upload e2e test reports
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: ${{ always() }}
        with:
          name: e2e-reports
          path: |
            e2e-report/
            e2e-results/
          retention-days: 3

  lhci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          lfs: true

      - name: Download website
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5
        with:
          name: website
          path: website/dist

      - name: Set up pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4

      - name: Set up Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Run Lighthouse tests
        run: pnpm run test:lhci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
